<?php

//========================================================================================================

// hard-coded field definition for intitiateven
// please use the 'ACF OpenStreetMap Field' plugin to add
// coordinates to an initiatief

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5f589cb3955cc',
		'title' => 'Data-initiatief: locatie en adres',
		'fields' => array(
			array(
				'center_lat' => 52.2345283,
				'center_lng' => 5.5206299,
				'zoom' => 7,
				'key' => 'field_5f58c08e264c0',
				'label' => 'Locatie op de kaart',
				'name' => 'openstreet_map',
				'type' => 'open_street_map',
				'instructions' => 'Kies hier een locatie op de kaart. Als je geen exact adres weet, zoek dan op plaatsnaam.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'raw',
				'layers' => array(
					0 => 'OpenStreetMap.Mapnik',
				),
				'allow_map_layers' => 1,
				'height' => 600,
				'max_markers' => '',
			),
			array(
				'key' => 'field_619f59ff89426',
				'label' => 'Adres',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Hieronder kun je een adres invoeren. Dit heeft geen invloed op de locatie op de kaart. Het adres wordt apart vermeld onder de lange tekst die het initiatief beschrijft.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5f80206f9c2f5',
				'label' => 'Straatnaam + huisnummer',
				'name' => 'locatie_straatnaam_huisnummer',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f8020c09c2f6',
				'label' => 'Postcode',
				'name' => 'locatie_postcode',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f87fec245e44',
				'label' => 'Plaatsnaam',
				'name' => 'locatie_plaatsnaam',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'initiatief',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'categories',
		),
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5f801513dfa08',
		'title' => 'Icoontje type data-initiatief',
		'fields' => array(
			array(
				'key' => 'field_5f801544f2817',
				'label' => 'Welk icoontje hoort hierbij?',
				'name' => 'initiatief_type_icon',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'community' => 'Community',
					'lab' => 'Lab',
					'onbekend' => 'Onbekend',
					'portaal' => 'Portaal',
					'strategie' => 'Strategie',
					'visualisatie' => 'Visualisatie',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'onbekend',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'initiatieftype',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_619f571e82dff',
		'title' => 'Innovatieproject: regievoerder, partners, locatie, adres',
		'fields' => array(
			array(
				'key' => 'field_619f5794ca13d',
				'label' => 'Regievoerder',
				'name' => 'innovatieproject_regievoerder',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_619f5750d729e',
				'label' => 'Partners',
				'name' => 'innovatieproject_partners',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'center_lat' => 52.2345283,
				'center_lng' => 5.5206299,
				'zoom' => 7,
				'key' => 'field_619f571e89aa0',
				'label' => 'Locatie op de kaart',
				'name' => 'openstreet_map',
				'type' => 'open_street_map',
				'instructions' => 'Kies hier een locatie op de kaart. Als je geen exact adres weet, zoek dan op plaatsnaam.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'raw',
				'layers' => array(
					0 => 'OpenStreetMap.Mapnik',
				),
				'allow_map_layers' => 1,
				'height' => 600,
				'max_markers' => '',
			),
			array(
				'key' => 'field_619f5a89a82d2',
				'label' => 'Adres',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Hieronder kun je een adres invoeren. Dit heeft geen invloed op de locatie op de kaart. Het adres wordt apart vermeld onder de lange tekst die het project beschrijft.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_619f571e89abc',
				'label' => 'Straatnaam + huisnummer',
				'name' => 'locatie_straatnaam_huisnummer',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_619f571e89ad6',
				'label' => 'Postcode',
				'name' => 'locatie_postcode',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_619f571e89af2',
				'label' => 'Plaatsnaam',
				'name' => 'locatie_plaatsnaam',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'innovatieproject',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'categories',
		),
		'active' => true,
		'description' => '',
	));


		acf_add_local_field_group(array(
			'key' => 'group_61ae455e70588',
			'title' => 'kleur marker',
			'fields' => array(
				array(
					'key' => 'field_61ae456e12c28',
					'label' => 'kleur marker',
					'name' => 'organisatie_type_icon',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(

						'r' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-r.svg" alt="" height="20"> R',
						'p' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-p.svg" alt="" height="20"> P',
						'g' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-g.svg" alt="" height="20"> G',
						'o' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-o.svg" alt="" height="20"> O',
						'w' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-w.svg" alt="" height="20"> W',
						'rhs-paars' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-paars.svg" alt="" height="20"> paars',
						'rhs-robijnrood' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-robijnrood.svg" alt="" height="20"> robijnrood',
						'rhs-rood' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-rood.svg" alt="" height="20"> rood',
						'rhs-roze' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-roze.svg" alt="" height="20"> roze',
						'rhs-violet' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-violet.svg" alt="" height="20"> violet',
						'rhs-oranje' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-oranje.svg" alt="" height="20"> oranje',
						'rhs-mosgroen' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-mosgroen.svg" alt="" height="20"> mosgroen',
						'rhs-mintgroen' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-mintgroen.svg" alt="" height="20"> mintgroen',
						'rhs-donkerblauw' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-donkerblauw.svg" alt="" height="20"> donkerblauw',
						'rhs-donkerbruin' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-donkerbruin.svg" alt="" height="20"> donkerbruin',
						'rhs-donkergeel' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-donkergeel.svg" alt="" height="20"> donkergeel',
						'rhs-donkergroen' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-donkergroen.svg" alt="" height="20"> donkergroen',
						'rhs-groen' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-groen.svg" alt="" height="20"> groen',
						'rhs-hemelblauw' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-hemelblauw.svg" alt="" height="20"> hemelblauw',
						'rhs-lichtblauw' => '<img src="/wp-content/plugins/ictuwp-plugin-initiatievenkaart/public/css/images/marker-rhs-lichtblauw.svg" alt="" height="20"> lichtblauw',

					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => 'rhs-lichtblauw',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'taxonomy',
						'operator' => '==',
						'value' => 'organisatie',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
		));




endif;
